# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-06-30 14:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dictionary', '0002_approval'),
    ]

    operations = [
        migrations.AddField(
            model_name='phrase',
            name='description',
            field=models.TextField(blank=True, verbose_name='description'),
        ),
    ]
